import type { User, ClassLevel, Subject, Topic, Question, Paper } from "./types"

export const MOCK_USERS: User[] = [
  { id: "1", name: "Admin Master", email: "admin@papersetter.com", role: "master" },
  { id: "2", name: "Sarah Teacher", email: "sarah@school.com", role: "teacher" },
  { id: "3", name: "John Student", email: "john@student.com", role: "student" },
]

export const CLASSES: ClassLevel[] = [
  "SKG",
  "JKG",
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th",
  "11th",
  "12th",
]

export const SUBJECTS: Subject[] = [
  { id: "eng_10", name: "English", classLevel: "10th" },
  { id: "reasoning_10", name: "Reasoning", classLevel: "10th" },
  { id: "math_10", name: "Mathematics", classLevel: "10th" },
  { id: "sci_10", name: "Science", classLevel: "10th" },
  { id: "phy_12", name: "Physics", classLevel: "12th" },
  { id: "chem_12", name: "Chemistry", classLevel: "12th" },
  { id: "bio_12", name: "Biology", classLevel: "12th" },
]

export const TOPICS: Topic[] = [
  { id: "reading", subjectId: "eng_10", name: "Reading Comprehension" },
  { id: "grammar", subjectId: "eng_10", name: "Grammar" },
  { id: "vocab", subjectId: "eng_10", name: "Vocabulary" },
  { id: "logical", subjectId: "reasoning_10", name: "Logical Reasoning" },
  { id: "spatial", subjectId: "reasoning_10", name: "Spatial Reasoning" },
  { id: "algebra", subjectId: "math_10", name: "Algebra" },
  { id: "geometry", subjectId: "math_10", name: "Geometry" },
  { id: "bio", subjectId: "sci_10", name: "Biology" },
  { id: "chemistry", subjectId: "sci_10", name: "Chemistry" },
  { id: "physics", subjectId: "sci_10", name: "Physics" },
]

export const ALL_MOCK_QUESTIONS: Question[] = [
  // ========== PAPER CODE 003 - CLASS 10 ==========
  // ENGLISH SECTION - Reading Comprehension with Passage
  {
    id: "003-eng-001",
    type: "paragraph",
    classLevel: "10th",
    subjectId: "eng_10",
    topicId: "reading",
    marks: 3,
    negativeMarks: 0,
    difficulty: "medium",
    createdAt: "2024-01-15",
    paragraphText:
      "The rattlesnake rattles before it strikes, and this warning is valuable. When the rattlesnake warns, the sound is a warning mechanism. Other animals with warning systems include skunks, which spray when threatened. The rattlesnake's rattle is made of modified tail scales that vibrate when muscles contract. These rattles increase in number each time the snake sheds its skin. A full-grown rattlesnake can have up to 15-20 rattles in its tail.",
    subQuestions: [
      {
        id: "003-eng-001-1",
        type: "mcq_text",
        classLevel: "10th",
        subjectId: "eng_10",
        topicId: "reading",
        marks: 1,
        negativeMarks: 0,
        difficulty: "easy",
        createdAt: "2024-01-15",
        questionText: "Why does the rattlesnake rattle?",
        options: [
          { id: "a", text: "To attract mates", isCorrect: false },
          { id: "b", text: "As a warning mechanism before striking", isCorrect: true },
          { id: "c", text: "To communicate with other snakes", isCorrect: false },
          { id: "d", text: "To regulate body temperature", isCorrect: false },
        ],
      },
      {
        id: "003-eng-001-2",
        type: "mcq_text",
        classLevel: "10th",
        subjectId: "eng_10",
        topicId: "reading",
        marks: 1,
        negativeMarks: 0,
        difficulty: "easy",
        createdAt: "2024-01-15",
        questionText: "What are rattles made of?",
        options: [
          { id: "a", text: "Modified vertebrae", isCorrect: false },
          { id: "b", text: "Hardened skin", isCorrect: false },
          { id: "c", text: "Modified tail scales", isCorrect: true },
          { id: "d", text: "Calcium deposits", isCorrect: false },
        ],
      },
      {
        id: "003-eng-001-3",
        type: "mcq_text",
        classLevel: "10th",
        subjectId: "eng_10",
        topicId: "reading",
        marks: 1,
        negativeMarks: 0,
        difficulty: "medium",
        createdAt: "2024-01-15",
        questionText: "How many rattles can a full-grown rattlesnake have?",
        options: [
          { id: "a", text: "5-10", isCorrect: false },
          { id: "b", text: "15-20", isCorrect: true },
          { id: "c", text: "25-30", isCorrect: false },
          { id: "d", text: "30-50", isCorrect: false },
        ],
      },
    ],
  },

  // ENGLISH SECTION - Vocabulary/Grammar
  {
    id: "003-eng-002",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "eng_10",
    topicId: "grammar",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "Choose the correct spelling:",
    options: [
      { id: "a", text: "Acommodation", isCorrect: false },
      { id: "b", text: "Accommodation", isCorrect: true },
      { id: "c", text: "Accomodation", isCorrect: false },
      { id: "d", text: "Acommodtion", isCorrect: false },
    ],
  },

  {
    id: "003-eng-003",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "eng_10",
    topicId: "grammar",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "Fill in the blank: 'She _____ to the market yesterday.'",
    options: [
      { id: "a", text: "goes", isCorrect: false },
      { id: "b", text: "go", isCorrect: false },
      { id: "c", text: "went", isCorrect: true },
      { id: "d", text: "going", isCorrect: false },
    ],
  },

  // REASONING SECTION
  {
    id: "003-reason-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "reasoning_10",
    topicId: "logical",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "If all roses are flowers and some flowers fade, then:",
    options: [
      { id: "a", text: "All roses fade", isCorrect: false },
      { id: "b", text: "Some roses fade", isCorrect: true },
      { id: "c", text: "No roses fade", isCorrect: false },
      { id: "d", text: "Some flowers are not roses", isCorrect: false },
    ],
  },

  {
    id: "003-reason-002",
    type: "matching",
    classLevel: "10th",
    subjectId: "reasoning_10",
    topicId: "logical",
    marks: 2,
    negativeMarks: 0.5,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "Match the following:",
    options: [
      { id: "1", text: "Carnivore" },
      { id: "2", text: "Herbivore" },
      { id: "3", text: "Omnivore" },
    ],
    correctMatches: [
      { optionId: "1", matchId: "lion" },
      { optionId: "2", matchId: "cow" },
      { optionId: "3", matchId: "bear" },
    ],
  },

  // ========== PAPER CODE 004 - CLASS 10 ==========
  // MATHEMATICS SECTION
  {
    id: "004-math-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "math_10",
    topicId: "algebra",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "Solve: 2x + 3 = 9",
    options: [
      { id: "a", text: "x = 2", isCorrect: false },
      { id: "b", text: "x = 3", isCorrect: true },
      { id: "c", text: "x = 4", isCorrect: false },
      { id: "d", text: "x = 5", isCorrect: false },
    ],
  },

  {
    id: "004-math-002",
    type: "short_answer",
    classLevel: "10th",
    subjectId: "math_10",
    topicId: "geometry",
    marks: 2,
    negativeMarks: 0,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "What is the area of a rectangle with length 5 cm and width 3 cm?",
    correctAnswer: "15 cm²",
  },

  {
    id: "004-math-003",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "math_10",
    topicId: "algebra",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "hard",
    createdAt: "2024-01-15",
    questionText: "Factorize: x² - 5x + 6",
    options: [
      { id: "a", text: "(x-2)(x-3)", isCorrect: true },
      { id: "b", text: "(x+2)(x+3)", isCorrect: false },
      { id: "c", text: "(x-1)(x-6)", isCorrect: false },
      { id: "d", text: "(x+2)(x-3)", isCorrect: false },
    ],
  },

  // SCIENCE SECTION
  {
    id: "004-sci-001",
    type: "true_false",
    classLevel: "10th",
    subjectId: "sci_10",
    topicId: "physics",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "The acceleration due to gravity is constant everywhere on Earth.",
    correctAnswer: false,
  },

  {
    id: "004-sci-002",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "sci_10",
    topicId: "chemistry",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "What is the chemical formula for table salt?",
    options: [
      { id: "a", text: "KCl", isCorrect: false },
      { id: "b", text: "NaCl", isCorrect: true },
      { id: "c", text: "CaCl₂", isCorrect: false },
      { id: "d", text: "MgCl₂", isCorrect: false },
    ],
  },

  {
    id: "004-sci-003",
    type: "paragraph",
    classLevel: "10th",
    subjectId: "sci_10",
    topicId: "bio",
    marks: 3,
    negativeMarks: 0,
    difficulty: "hard",
    createdAt: "2024-01-15",
    paragraphText:
      "Photosynthesis is the process by which plants convert light energy into chemical energy stored in glucose. This process occurs primarily in the leaves of plants, specifically in the chloroplasts. The equation for photosynthesis is: 6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. The process has two main stages: the light-dependent reactions occurring in the thylakoid membranes, and the light-independent reactions (Calvin cycle) occurring in the stroma.",
    subQuestions: [
      {
        id: "004-sci-003-1",
        type: "mcq_text",
        classLevel: "10th",
        subjectId: "sci_10",
        topicId: "bio",
        marks: 1,
        negativeMarks: 0.25,
        difficulty: "easy",
        createdAt: "2024-01-15",
        questionText: "Where does photosynthesis primarily occur?",
        options: [
          { id: "a", text: "In the roots", isCorrect: false },
          { id: "b", text: "In the leaves", isCorrect: true },
          { id: "c", text: "In the stem", isCorrect: false },
          { id: "d", text: "In the flowers", isCorrect: false },
        ],
      },
      {
        id: "004-sci-003-2",
        type: "mcq_text",
        classLevel: "10th",
        subjectId: "sci_10",
        topicId: "bio",
        marks: 1,
        negativeMarks: 0.25,
        difficulty: "medium",
        createdAt: "2024-01-15",
        questionText: "What is the main product of photosynthesis?",
        options: [
          { id: "a", text: "Oxygen", isCorrect: false },
          { id: "b", text: "Glucose", isCorrect: true },
          { id: "c", text: "Water", isCorrect: false },
          { id: "d", text: "Carbon dioxide", isCorrect: false },
        ],
      },
      {
        id: "004-sci-003-3",
        type: "short_answer",
        classLevel: "10th",
        subjectId: "sci_10",
        topicId: "bio",
        marks: 1,
        negativeMarks: 0,
        difficulty: "hard",
        createdAt: "2024-01-15",
        questionText: "Name the two stages of photosynthesis.",
        correctAnswer: "Light-dependent reactions and light-independent reactions (Calvin cycle)",
      },
    ],
  },

  // ========== PAPER CODE 005 - CLASS 10 ==========
  {
    id: "005-eng-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "eng_10",
    topicId: "vocab",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "What is the synonym of 'benevolent'?",
    options: [
      { id: "a", text: "Cruel", isCorrect: false },
      { id: "b", text: "Kind", isCorrect: true },
      { id: "c", text: "Angry", isCorrect: false },
      { id: "d", text: "Sad", isCorrect: false },
    ],
  },

  {
    id: "005-math-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "math_10",
    topicId: "geometry",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "The sum of angles in a triangle is:",
    options: [
      { id: "a", text: "90°", isCorrect: false },
      { id: "b", text: "180°", isCorrect: true },
      { id: "c", text: "270°", isCorrect: false },
      { id: "d", text: "360°", isCorrect: false },
    ],
  },

  // ========== PAPER CODE 006 - CLASS 12 PHYSICS ==========
  {
    id: "006-phy-001",
    type: "mcq_text",
    classLevel: "12th",
    subjectId: "phy_12",
    topicId: "physics",
    marks: 1,
    negativeMarks: 0.33,
    difficulty: "hard",
    createdAt: "2024-01-15",
    questionText: "What is the SI unit of force?",
    options: [
      { id: "a", text: "Dyne", isCorrect: false },
      { id: "b", text: "Newton", isCorrect: true },
      { id: "c", text: "Erg", isCorrect: false },
      { id: "d", text: "Joule", isCorrect: false },
    ],
  },

  {
    id: "006-phy-002",
    type: "short_answer",
    classLevel: "12th",
    subjectId: "phy_12",
    topicId: "physics",
    marks: 2,
    negativeMarks: 0,
    difficulty: "hard",
    createdAt: "2024-01-15",
    questionText: "State Newton's second law of motion.",
    correctAnswer: "F = ma (Force equals mass times acceleration)",
  },

  // ========== PAPER CODE 007 - CLASS 12 CHEMISTRY ==========
  {
    id: "007-chem-001",
    type: "mcq_text",
    classLevel: "12th",
    subjectId: "chem_12",
    topicId: "chemistry",
    marks: 1,
    negativeMarks: 0.33,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "What is the atomic number of Carbon?",
    options: [
      { id: "a", text: "4", isCorrect: true },
      { id: "b", text: "6", isCorrect: false },
      { id: "c", text: "8", isCorrect: false },
      { id: "d", text: "12", isCorrect: false },
    ],
  },

  {
    id: "007-chem-002",
    type: "true_false",
    classLevel: "12th",
    subjectId: "chem_12",
    topicId: "chemistry",
    marks: 1,
    negativeMarks: 0.33,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "Molar mass of H₂O is 18 g/mol.",
    correctAnswer: true,
  },

  // ========== PAPER CODE 008 - CLASS 12 BIOLOGY ==========
  {
    id: "008-bio-001",
    type: "paragraph",
    classLevel: "12th",
    subjectId: "bio_12",
    topicId: "bio",
    marks: 3,
    negativeMarks: 0,
    difficulty: "hard",
    createdAt: "2024-01-15",
    paragraphText:
      "DNA (deoxyribonucleic acid) is the molecule that carries genetic instructions for all living organisms. It consists of two complementary strands wound in a double helix structure. Each strand is made up of nucleotides, which consist of a deoxyribose sugar, a phosphate group, and a nitrogenous base (adenine, guanine, cytosine, or thymine). The base pairs are always complementary: adenine pairs with thymine, and guanine pairs with cytosine. This complementarity ensures accurate replication of genetic information.",
    subQuestions: [
      {
        id: "008-bio-001-1",
        type: "mcq_text",
        classLevel: "12th",
        subjectId: "bio_12",
        topicId: "bio",
        marks: 1,
        negativeMarks: 0.33,
        difficulty: "easy",
        createdAt: "2024-01-15",
        questionText: "What does DNA stand for?",
        options: [
          { id: "a", text: "Deoxyribonucleic acid", isCorrect: true },
          { id: "b", text: "Diribonucleic acid", isCorrect: false },
          { id: "c", text: "Dynamic nucleic acid", isCorrect: false },
          { id: "d", text: "Deoxinucleic acid", isCorrect: false },
        ],
      },
      {
        id: "008-bio-001-2",
        type: "mcq_text",
        classLevel: "12th",
        subjectId: "bio_12",
        topicId: "bio",
        marks: 1,
        negativeMarks: 0.33,
        difficulty: "medium",
        createdAt: "2024-01-15",
        questionText: "Which base pairs with Adenine?",
        options: [
          { id: "a", text: "Guanine", isCorrect: false },
          { id: "b", text: "Cytosine", isCorrect: false },
          { id: "c", text: "Thymine", isCorrect: true },
          { id: "d", text: "Uracil", isCorrect: false },
        ],
      },
      {
        id: "008-bio-001-3",
        type: "short_answer",
        classLevel: "12th",
        subjectId: "bio_12",
        topicId: "bio",
        marks: 1,
        negativeMarks: 0,
        difficulty: "hard",
        createdAt: "2024-01-15",
        questionText: "Describe the structure of DNA.",
        correctAnswer: "Double helix structure consisting of two complementary strands with complementary base pairing",
      },
    ],
  },

  {
    id: "008-bio-002",
    type: "mcq_text",
    classLevel: "12th",
    subjectId: "bio_12",
    topicId: "bio",
    marks: 1,
    negativeMarks: 0.33,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "The basic unit of life is:",
    options: [
      { id: "a", text: "Atom", isCorrect: false },
      { id: "b", text: "Cell", isCorrect: true },
      { id: "c", text: "Molecule", isCorrect: false },
      { id: "d", text: "Tissue", isCorrect: false },
    ],
  },

  // ========== PAPER CODE 009 - CLASS 10 (Additional) ==========
  {
    id: "009-eng-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "eng_10",
    topicId: "grammar",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "Identify the correct sentence:",
    options: [
      { id: "a", text: "She go to school every day", isCorrect: false },
      { id: "b", text: "She goes to school every day", isCorrect: true },
      { id: "c", text: "She going to school every day", isCorrect: false },
      { id: "d", text: "She gone to school every day", isCorrect: false },
    ],
  },

  {
    id: "009-reason-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "reasoning_10",
    topicId: "spatial",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "If you are facing North and turn 90° clockwise, which direction are you facing?",
    options: [
      { id: "a", text: "South", isCorrect: false },
      { id: "b", text: "East", isCorrect: true },
      { id: "c", text: "West", isCorrect: false },
      { id: "d", text: "North", isCorrect: false },
    ],
  },

  // ========== PAPER CODE 010 - CLASS 10 (Additional) ==========
  {
    id: "010-math-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "math_10",
    topicId: "algebra",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "easy",
    createdAt: "2024-01-15",
    questionText: "What is 20% of 50?",
    options: [
      { id: "a", text: "5", isCorrect: false },
      { id: "b", text: "10", isCorrect: true },
      { id: "c", text: "15", isCorrect: false },
      { id: "d", text: "20", isCorrect: false },
    ],
  },

  {
    id: "010-sci-001",
    type: "mcq_text",
    classLevel: "10th",
    subjectId: "sci_10",
    topicId: "chemistry",
    marks: 1,
    negativeMarks: 0.25,
    difficulty: "medium",
    createdAt: "2024-01-15",
    questionText: "What is the pH of pure water at 25°C?",
    options: [
      { id: "a", text: "6", isCorrect: false },
      { id: "b", text: "7", isCorrect: true },
      { id: "c", text: "8", isCorrect: false },
      { id: "d", text: "9", isCorrect: false },
    ],
  },
]

export const RECENT_PAPERS = [
  {
    id: "paper_inno_003",
    title: "INNOSAT Class 10 - CODE 003",
    date: "2025-10-03",
    status: "Generated",
    class: "10th",
    totalMarks: 160,
  },
  {
    id: "paper_inno_004",
    title: "INNOSAT Class 10 - CODE 004",
    date: "2025-10-04",
    status: "Generated",
    class: "10th",
    totalMarks: 160,
  },
  {
    id: "paper_inno_005",
    title: "INNOSAT Class 10 - CODE 005",
    date: "2025-10-05",
    status: "Draft",
    class: "10th",
    totalMarks: 180,
  },
]

export const SAMPLE_PAPER: Paper = {
  id: "paper_inno_003",
  title: "INNOSAT Exam Paper - October Session",
  code: "003",
  class: "10th",
  date: "October 17, 2024",
  duration: "2 Hours 30 Minutes",
  totalMarks: 160,
  negativeMarks: "-0.25 for wrong MCQ, -0.33 for Class 12",
  instructions: [
    "This question paper contains multiple sections.",
    "All questions are compulsory.",
    "Use blue or black pen only for writing answers.",
    "Diagrams, if any, should be drawn neatly.",
    "In case of any disputes, the English version shall be final.",
  ],
  sections: [
    {
      id: "section_1",
      name: "English",
      marks: 40,
      questions: [
        {
          id: "003-eng-001",
          text: "Read the passage and answer the following questions (3 marks)",
          marks: 3,
          type: "paragraph",
        },
        {
          id: "003-eng-002",
          text: "Choose the correct spelling",
          marks: 1,
          type: "mcq",
        },
        {
          id: "003-eng-003",
          text: "Fill in the blank with correct tense",
          marks: 1,
          type: "mcq",
        },
      ],
    },
    {
      id: "section_2",
      name: "Reasoning",
      marks: 40,
      questions: [
        {
          id: "003-reason-001",
          text: "Logical reasoning question",
          marks: 1,
          type: "mcq",
        },
        {
          id: "003-reason-002",
          text: "Match the following",
          marks: 2,
          type: "matching",
        },
      ],
    },
    {
      id: "section_3",
      name: "Mathematics",
      marks: 40,
      questions: [
        {
          id: "004-math-001",
          text: "Solve the equation",
          marks: 1,
          type: "mcq",
        },
        {
          id: "004-math-002",
          text: "Area calculation problem",
          marks: 2,
          type: "short_answer",
        },
      ],
    },
    {
      id: "section_4",
      name: "Science",
      marks: 40,
      questions: [
        {
          id: "004-sci-001",
          text: "True or False statement",
          marks: 1,
          type: "true_false",
        },
        {
          id: "004-sci-002",
          text: "Chemical formula question",
          marks: 1,
          type: "mcq",
        },
        {
          id: "004-sci-003",
          text: "Read the passage about photosynthesis",
          marks: 3,
          type: "paragraph",
        },
      ],
    },
  ],
}
